# Generated by Django 6.0.1 on 2026-01-29 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['to_user', 'status'], name='api_friendr_to_user_001203_idx'), models.Index(fields=['from_user', 'status'], name='api_friendr_from_us_26913b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='friend_request_not_to_self'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_user'), name='unique_pending_friend_request')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1'], name='api_friends_user1_i_adbd6c_idx'), models.Index(fields=['user2'], name='api_friends_user2_i_dd85ff_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user1__lt', models.F('user2'))), name='friendship_user1_lt_user2'), models.UniqueConstraint(fields=('user1', 'user2'), name='unique_friendship_pair')],
            },
        ),
    ]
