# Generated by Django 6.0.1 on 2026-03-16 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-steps'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_dailyst_user_id_528b7e_idx'), models.Index(fields=['date'], name='api_dailyst_date_7eb16c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_steps_per_user_date')],
            },
        ),
    ]
