# Generated by Django 6.0.1 on 2026-04-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usertrackpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrackpoint',
            name='horizontal_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
