# Generated by Django 6.0.1 on 2026-04-30 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usertrackpoint_horizontal_accuracy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrackpoint',
            name='course',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertrackpoint',
            name='movement_state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='usertrackpoint',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertrackpoint',
            name='steps_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertrackpoint',
            name='recorded_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='MatchedTrackSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(db_index=True)),
                ('raw_points', models.JSONField(default=list)),
                ('display_points', models.JSONField(default=list)),
                ('movement_state', models.CharField(blank=True, max_length=32, null=True)),
                ('signal_quality', models.CharField(blank=True, max_length=16, null=True)),
                ('matching_confidence', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fallback', 'Fallback raw'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_track_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
