# Generated by Django 6.0.1 on 2026-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usertrackpoint_course_usertrackpoint_movement_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrackpoint',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
