# Generated by Django 6.0.1 on 2026-04-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usertrackpoint_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedtracksegment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fallback', 'Fallback'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
    ]
