# Generated by Django 6.0.1 on 2026-05-05 17:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_matchedtracksegment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.group_avatar_upload_to),
        ),
    ]
