# Generated by Django 6.0.1 on 2026-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_group_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='goal_steps',
            field=models.PositiveIntegerField(default=300000),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
