# Generated by Django 6.0.1 on 2026-05-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='seen_by_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
