# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_friendrequest_seen_by_from_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlivelocation",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userlivelocation",
            name="movement_state",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userlivelocation",
            name="movement_kind",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userlivelocation",
            name="signal_quality",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="usertrackpoint",
            name="movement_kind",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="usertrackpoint",
            name="break_reason",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="usertrackpoint",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchedtracksegment",
            name="movement_kind",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="matchedtracksegment",
            name="break_reason",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="matchedtracksegment",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
