# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_map_confidence_and_break_reason"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usertrackpoint",
            index=models.Index(
                fields=["user", "day", "recorded_at"],
                name="api_tp_user_day_rec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchedtracksegment",
            index=models.Index(
                fields=["user", "day", "started_at"],
                name="api_mts_user_day_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchedtracksegment",
            index=models.Index(
                fields=["user", "day", "ended_at"],
                name="api_mts_user_day_end_idx",
            ),
        ),
    ]
