# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_track_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailysteps",
            name="goal_steps",
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_goal_steps",
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
